### PR TITLE
Patch for Moodle version 3.x

### PR DESCRIPTION
**Pull request by taboubi**
#4

### CODE REVIEW

**Comment by taboubi** [comment]
@danmarsden  were you able to find some free time to check my changes

**Comment by danmarsden** [comment]
I'm slammed right now - I have community stuff sitting in my backlog that has been there for several months... hopefully I'll clear some work and get to it sometime! - thanks for submitting it here for us to look at though!

**Comment by taboubi** [comment]
Hello @danmarsden ,
We noticed that the plugin moodle-quiz_randomsummary is not regularly updated (last update was 8 years ago), we have already made a pull request to migrate it to version 3.x but it was not still approved I know that you are very busy but we find that the plugin is very interesting and a big loss we want to become the maintainers of this plugin because we migrate it anyway during our Moodle migration. We have already migrated it for version 4.3 of Moodle. What do you think ?

At the University of Montreal we are a team of 6 developers.

thank you.

**Comment by taboubi** [comment]
Hi @danmarsden the link sent from github is broken can you do the transfert to our organisation https://github.com/StudiUM and  can you do us a maintainer in the moodle plugin repository here are the logins: 
salemsaidi, taboubii, leblangi, massicos , gurvan.giboire@umontreal.ca.
brokenrequest

thank you

**Comment by danmarsden** [comment]
Hi @taboubi - transfer to an org repo is only possible if you have access to that org repo (which I don't) - you should be able to transfer it there yourself after accepting the transfer into your own personal repo - if you already have a repo with the same name you may need to delete that first before accepting the transfer too. I've just aborted the transfer and sent another transfer request to see if that helps too.

You have been set as the lead maintainer on the moodle.org plugin entry so can add other maintainers yourself but let me know if you need a different user to be set as the lead maintainer and I can drop that in for you,

**Pull request closed without merging**
